name: Deploy MKDocs

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy image
        run: |
          export RELEASE=$(grep "MKDOCS_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}' | sed 's|"||g')
          docker build . --file Dockerfile --tag iceleaf/mkdocs:${RELEASE}
          docker tag iceleaf/mkdocs:${RELEASE} iceleaf/mkdocs:latest
          docker login  -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push iceleaf/mkdocs:${RELEASE}
          docker push iceleaf/mkdocs:latest
